Updated init script

diff --git a/roles/install-osprofiler/templates/init.d-template.j2 b/roles/install-osprofiler/templates/init.d-template.j2
--- a/roles/install-osprofiler/templates/init.d-template.j2
+++ b/roles/install-osprofiler/templates/init.d-template.j2
@@ -1,79 +1,157 @@
-#!/bin/sh
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          osprofiler
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: osprofiler
+# Description:       This starts and stop the osprofiler service.
+### END INIT INFO
 
-USER={{user}}
-SERVICE_NAME={{service_name}}
-DAEMON={{daemon}}
-DAEMON_OPTS="{{daemon_opts}}"
-PIDFILE={{pidfile}}
+# Author: Sudarshan Acharya <sudarshan.acharya@rackspace.com>
+#
 
-if [ ! -x $DAEMON ]; then
-  echo "ERROR: Can't execute $DAEMON."
-  exit 1
-fi
+# Do NOT "set -e"
 
-start_service() {
-  echo -n " * Starting $SERVICE_NAME... "
-  start-stop-daemon -Sq --chuid $USER -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
-  e=$?
-  if [ $e -eq 1 ]; then
-    echo "already running"
-    return
-  fi
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+RUNAS="{{ user }}"
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="{{ service_name }}"
+NAME="{{ service_name }}"
+DAEMON="{{ daemon }}"
+DAEMON_ARGS="{{ daemon_opts }}"
+PIDFILE="{{ pidfile }}"
+SCRIPTNAME=/etc/init.d/$NAME
 
-  if [ $e -eq 255 ]; then
-    echo "couldn't start :("
-    exit 1
-  fi
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-  echo "done"
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --chuid $RUNAS --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --make-pidfile --chuid $RUNAS --pidfile $PIDFILE --background --exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
 
-stop_service() {
-  echo -n " * Stopping $SERVICE_NAME... "
-  start-stop-daemon -Kq -R 10 -p $PIDFILE
-  e=$?
-  if [ $e -eq 1 ]; then
-    echo "not running"
-    return
-  fi
-
-  echo "done"
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --chuid $RUNAS --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --chuid $RUNAS --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
 }
 
-status_service() {
-  printf "%-50s" "Checking $SERVICE_NAME..."
-  if [ -f $PIDFILE ]; then
-    PID=`cat $PIDFILE`
-    if [ -z "`ps axf | grep ${PID} | grep -v grep`"]; then
-      printf "%s\n" "Process dead but pidfile exists"
-      exit 1 
-    else
-      echo "Running"
-    fi
-  else
-    printf "%s\n" "Service not running"
-    exit 3 
-  fi
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --chuid $RUNAS --pidfile $PIDFILE --name $NAME
+	return 0
 }
 
 case "$1" in
-  status)
-    status_service
-    ;;
   start)
-    start_service
-    ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   stop)
-    stop_service
-    ;;
-  restart)
-    stop_service
-    start_service
-    ;;
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
   *)
-  echo "Usage: service $SERVICE_NAME {start|stop|restart|status}" >&2
-  exit 1   
-  ;;
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
